### ISSUE TITLE
"Virtual Web" refactor

### ISSUE THREAD

**Issue by pfrazee** [pfrazee/local#109]
The next version of Local is going to try to reduce some of its un-needed complexity. Some of the generality of the existing versions have led to an overly-taxing environment; in particular, understanding the local:// namespace has been difficult (for newcomers and for myself), and effectively employing links has been hard to do.

**Tasks**
- [x] Hash URI routing
- [x] Move to local.at
- [x] Transparent worker proxy
- [x] Refactored request/response API
- [x] Link tools
- [x] Clients
- [x] Simplified mimetypes
- [ ] Update documentation

**Hash URIs**

Local is going to take the view that it's building a "virtual web" - a namespace which is dependent on a live host environment (eg the document or a worker). To signify this, it is going to drop its local:// scheme, and instead shift to the pound-sign prefix (deriving from the single-page app concept of hash-uris). Therefore, a server which was previously addressed at `local://hosts` will now be found at `#hosts`.

This enables workers to drop the source-path envelope. Instead of `local://foo.com(/js/bar.js)/baz`, the server is addressed at `https://foo.com/js/bar.js#baz`. Like-wise, a document's service could be addressed at `https://foo.com/home.html#service/path` (and perhaps reached by creating the page in a popup).

**local.at**

Instead of adding servers, local will add paths in the current environment. The environment, therefore, becomes a single server. `local.addServer(domain, fn)` becomes `local.at(path, fn)`. The path may be a regex; the match results will go in `req.pathd`. The hash prefix is optional in `at`, so the toplevel may be specified as `local.at('#', fn)` or `local.at('', fn)` for instance.

**Transparent Worker Proxy**

The worker bridge-proxy no longer exists; instead, workers have their namespace overlaid onto their host environment's. That is, `local.GET('#hosts')` will fetch from the host page's path (registered with `local.at('hosts', ...)`). To address its own paths, it uses the `#self` special path (eg `local.GET('#self/inner-path')`.

Workers can not directly access the public Web - only the environment's virtual web. However, the host may create a proxy path (eg `#web/https://foobar.com`).

**Simplified Request/Response API**

Requests and responses will split into two different interfaces: one for incoming, one for outgoing. 

_Outgoing Request_

Can be created with a simplified `dispatch` function. Request sugars (`GET`, `POST`, `PUT`, etc) will be put in the global scope. Outgoing request objects and the response promise from `dispatch` will be combined. Common headers will be made functions (eg `.Authorization`, `ContentType`) while other headers can be added with the `header()` function.

Outgoing request objects will also have stream functions `write` and `end` which must be called to send the request. The headers cannot be send after `write` or `end`.

Requests created with `dispatch` or a sugar (GET, POST) will automatically call `bufferResponse` and call the created request's `end` function on the next tick. If the consuming app wants to stream the request or response over a long period, it can create the request manually (`new local.Request(options)`) and start the request with either `start()`, `write()`, or `end()`.

A pipe function streams incoming requests and responses. On outgoing requests, it actually passes through to the incoming response and takes a stream to receive the data. Headers which are not already set will transfer over:

``` js
local.at('#userpipe', function(req, res) {
  if (req.params.src) {
    GET(req.params.src).pipe(POST('#users'));
  } else if (req.ContentType) {
    req.pipe(POST('#users'));
  }
}
```

_Incoming Request_

Incoming request objects will put all headers in the top object (out of `headers`) and strip the dashes while keeping camel-case (that is `Content-Type` will be `req.ContentType`). The incoming request method will be set (in all uppercase) as a request object (eg `req.HEAD`).

A `buffer()` function will receive the stream, parse it and pass it to a callback (eg `req.buffer(function(body) { body.foo })`). However, it is better to just use the request object's `bufferResponse()` function.

The pipe function takes an outgoing request or response and streams the incoming data to that stream.

_Outgoing Response_

The outgoing response has functions for all response codes (eg `res.s200()`, `res.s404()`). Outgoing response objects will use header functions like outgoing requests. Headers may be set until `write` or `end`.

_Incoming Response_

Incoming response objects will use header values like incoming requests. It will also have the `data`, `end`, and `buffer` sugars.

The pipe function takes an outgoing request or response and streams the incoming data to that stream.

**Link Tools**

Incoming responses have their links parsed into `res.links`. It will have the `query` and `first` function to quickly fetch links from it. Links have an `is` function added to do queries on it (any `is` attribute will be reassigned to `_is`):

``` js
res.links.first('self').is('service'); // => true
```

Outgoing responses have the `link` function to simplify setting the link header. It adds to the link header (rather than overwriting it) and includes the following forms:

``` js
res.link({ href: '#', rel: 'self' });
res.link('#shop', 'service', { title: 'Shop Service' });
res.link([
  { href: '#users', rel: 'collection' },
  { href: '#orders', rel: 'orders' }
]);
res.link(
  ['href',   'rel',        'title'],
  '#news',   'service',    'Latest News',
  '#events', 'collection', 'Todays Events'
)
```

**Clients**

Agent will be renamed to client. It will include common reltype sugars for `follow` (eg `client.collection('users').item('bob')`). It will be usable as a stand-in for URLs (as well as carrying its own dispatch functions). A toplevel `from` sugar will be set for `local.client`.

**Additional/Misc**

Common mimetypes may drop their prefix (`html` -> `text/html`).

**Example worker**

``` js
local.at('#', function(req, res) {
    res.link(
        ['href', 'rel',          'title']
        '#',     'self service', 'About Renderer'
    ));
    if (req.HEAD) {
        return res.s204()
            .ContentType('html')
            .end();
    }
    if (!req.GET) { return res.s405('bad method').Allow('HEAD, GET').end(); }
    HEAD('#selection/0')
        .Authorization(req.Authorization)
        .end()
        .then(function(res2) {
            var selfLink = res2.links.first('self');

            var html = '';
            if (selfLink) {
                if (selfLink.is('stdrel.com/media')) {
                    var mime = selfLink.type || 'text/plain';
                    if (mime == 'text/plain') mime = 'plain-text';
                    else mime = mime.split('/')[1];
                    html += '<p>Raw media ('+mime+') - nothing else is known about this file.</p>';
                } else if (selfLink.is('stdrel.com/rel')) {
                    html += '<p>This is a "relation type." It explains how a location on the Web behaves, and is the basis of Layer1\'s structure.</p>';
                }

                if (selfLink.id) { html += '<small class="text-muted">ID</small> '+util.escapeHTML(selfLink.id)+'<br>'; }
                if (selfLink.rel) {
                    html += '<small class="text-muted">TYPE</small> '+util.decorateReltype(selfLink.rel);
                    if (selfLink.type) { html += ' '+util.escapeHTML(selfLink.type); }
                    html += '<br>';
                }
                if (selfLink.href) { html += '<small class="text-muted">HREF</small> <a href="'+util.escapeHTML(selfLink.href)+'" target=_blank>'+util.escapeHTML(selfLink.href)+'</a><br>'; }
                if (selfLink.created_at) { html += '<small class="text-muted">ADDED</small> '+((new Date(+selfLink.created_at)).toLocaleTimeString())+'<br>'; }
            }

            res.s200().ContentType('html').end(html);
        })
        .fail(function(res2) { res2.pipe(res.s502()); })
});
```

**Additional examples**

``` js
// clients
var host = local.client('#');
GET(host.collection('selection').item(0)).end();
GET(from('#').collection('selection').item(0)).end();

// piping
GET('#foo').pipe(res.s200())
GET('http://foo.com/users').pipe(POST('#users'))
function (req, res) { req.pipe(POST('#users')); } 
```
